---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: ".forestry/content/articles"
  label: News & Resources
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - content-type-article
- type: directory
  path: ".forestry/content/careers"
  label: Careers
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - content-type-career
- type: directory
  path: ".forestry/content/pages"
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - content-type-page
- type: heading
  label: Global Settings
- type: document
  path: ".forestry/content/settings/config.json"
  label: Site Info
- type: document
  path: ".forestry/content/settings/contact.json"
  label: Contact Info
- type: document
  path: ".forestry/content/settings/header.json"
  label: Header
- type: document
  path: ".forestry/content/settings/headerMobile.json"
  label: Header Mobile
- type: document
  path: ".forestry/content/settings/footer.json"
  label: Footer
- type: document
  path: ".forestry/content/settings/career.json"
  label: Career Options
upload_dir: ".forestry/content/images"
public_path: "/.forestry/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
