---
label: 'Global Settings: Header Mobile'
hide_body: false
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - header-mobile-block-top-navigation
  - header-mobile-block-bottom-navigation
  config:
    min: 
    max: 
pages:
- ".forestry/content/settings/headerMobile.json"
