---
label: 'Global Settings: Header'
hide_body: true
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - header-logo
  config:
    min: 
    max: 
pages:
- ".forestry/content/settings/header.json"
