---
label: 'Global Settings: Footer'
hide_body: true
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - footer-links
  - footer-quotes
  config:
    min: 
    max: 
- name: bottomRow
  type: blocks
  label: Bottom Row
  template_types: []
  config:
    min: 
    max: 
pages:
- ".forestry/content/settings/footer.json"
