---
label: 'Global Settings: Header'
hide_body: true
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - header-call-button
  - header-contact-button
  - header-fill-space
  - header-logo
  - header-links
  - header-quote-menu
  - header-user-menu
  config:
    min: 
    max: 
pages:
- ".forestry/content/settings/header.json"
