---
label: 'Global Settings: Footer'
hide_body: true
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - footer-quotes
  - footer-sitemap
  config:
    min: 
    max: 
pages:
- ".forestry/content/settings/footer.json"
